# Generated by Django 5.2.13 on 2026-04-09 06:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAnalysisRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this analysis job.', primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', help_text='Current lifecycle state of the analysis job.', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, help_text='When the ML pipeline began processing this request.', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the ML pipeline finished or encountered a fatal error.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Image Analysis Request',
                'verbose_name_plural': 'Image Analysis Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(height_field='height', help_text='The physical image file stored on the local filesystem.', upload_to='analysis_images/%Y/%m/%d/', width_field='width')),
                ('original_filename', models.CharField(blank=True, help_text='The original filename for reference.', max_length=255)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes.', null=True)),
                ('width', models.IntegerField(blank=True, help_text='Automated pixel width.', null=True)),
                ('height', models.IntegerField(blank=True, help_text='Automated pixel height.', null=True)),
                ('latitude', models.FloatField(blank=True, help_text='Geospatial latitude coordinate.', null=True)),
                ('longitude', models.FloatField(blank=True, help_text='Geospatial longitude coordinate.', null=True)),
                ('exif_data', models.JSONField(blank=True, default=dict, help_text='Extracted EXIF metadata in JSON format.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(help_text='The parent analysis request this image belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_images', to='api.imageanalysisrequest')),
            ],
            options={
                'verbose_name': 'Uploaded Image',
                'verbose_name_plural': 'Uploaded Images',
            },
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deepfake', models.BooleanField(db_index=True, default=False, help_text='Indicates if the image was flagged as a potential deepfake.')),
                ('deepfake_score', models.FloatField(blank=True, help_text='The probability score from the deepfake detection model.', null=True)),
                ('forensics', models.JSONField(blank=True, default=dict, help_text='Structured data from the forensics analysis module.')),
                ('geo_verification', models.JSONField(blank=True, default=dict, help_text='Cross-reference results between metadata and visual landmarks.')),
                ('objects_detected', models.JSONField(blank=True, default=list, help_text='A list of detected objects with confidence and coordinates.')),
                ('alpr', models.JSONField(blank=True, default=list, help_text='Detected vehicle license plate information.')),
                ('processing_time_ms', models.IntegerField(default=0, help_text='Execution time of the ML pipeline in milliseconds.')),
                ('error_message', models.TextField(blank=True, default='', help_text='Populated with traceback or error info if analysis fails.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.OneToOneField(help_text='The specific image this result belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='result', to='api.uploadedimage')),
            ],
            options={
                'verbose_name': 'Analysis Result',
                'verbose_name_plural': 'Analysis Results',
            },
        ),
    ]
