# Generated by Django 5.0.14 on 2026-04-29 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_migrate_uploadedimage_to_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='image_description',
            field=models.JSONField(blank=True, default=dict, help_text='Detailed image description generated by Gemma LLM when image is authentic.'),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='request',
            field=models.OneToOneField(help_text='The specific analysis request this result belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='result', to='api.imageanalysisrequest'),
        ),
        migrations.AlterField(
            model_name='imageanalysisrequest',
            name='file',
            field=models.ImageField(height_field='height', help_text='The physical image file stored on the local filesystem.', upload_to='analysis_images/%Y/%m/%d/', width_field='width'),
        ),
        migrations.AlterField(
            model_name='imageanalysisrequest',
            name='original_filename',
            field=models.CharField(blank=True, help_text='The original filename for reference.', max_length=255),
        ),
    ]
