# Generated by Django 5.0.14 on 2026-05-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_analysisresult_image_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='distance_estimation',
            field=models.JSONField(blank=True, default=dict, help_text='Distance estimation data from Depth Anything V2 + object detection.'),
        ),
    ]
